/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#00BFFF",
        secondary: "#87CEFA",
        tertiary: "#ADD8E6",
        highlight: "#87CEEB",
        dark: "#485493",
      },
      fontFamily: {
        sans: [
          "Pretendard",
          "-apple-system",
          "BlinkMacSystemFont",
          "system-ui",
          "Roboto",
          "Helvetica Neue",
          "Segoe UI",
          "Apple SD Gothic Neo",
          "Noto Sans KR",
          "Malgun Gothic",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "sans-serif",
        ],
        pretendard: ["Pretendard", "sans-serif"],
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1.5", letterSpacing: "0.025em" }],
        sm: ["0.875rem", { lineHeight: "1.5", letterSpacing: "0.025em" }],
        base: ["1rem", { lineHeight: "1.6", letterSpacing: "0.025em" }],
        lg: ["1.125rem", { lineHeight: "1.6", letterSpacing: "0.025em" }],
        xl: ["1.25rem", { lineHeight: "1.6", letterSpacing: "0.025em" }],
        "2xl": ["1.5rem", { lineHeight: "1.5", letterSpacing: "0.025em" }],
        "3xl": ["1.875rem", { lineHeight: "1.4", letterSpacing: "0.025em" }],
        "4xl": ["2.25rem", { lineHeight: "1.3", letterSpacing: "0.025em" }],
        "5xl": ["3rem", { lineHeight: "1.2", letterSpacing: "0.025em" }],
        "6xl": ["3.75rem", { lineHeight: "1.1", letterSpacing: "0.025em" }],
        "7xl": ["4.5rem", { lineHeight: "1.1", letterSpacing: "0.025em" }],
        "8xl": ["6rem", { lineHeight: "1", letterSpacing: "0.025em" }],
        "9xl": ["8rem", { lineHeight: "1", letterSpacing: "0.025em" }],
      },
      letterSpacing: {
        tighter: "-0.05em",
        tight: "-0.025em",
        normal: "0",
        wide: "0.025em",
        wider: "0.05em",
        widest: "0.1em",
      },
    },
  },
  plugins: [],
};
